# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bad5aa8eacbc8210a7985311e45f07c70e0011c7898af4ede3ed54de6cbb3f4fdf44952cb8abf3b347efbf3e440d00902ecd625a5a8605404fa9c09f0ac2536c

test:
  secret_key_base: d29383102f2b951a731ce6408ecd237456739eee61be057e148473448d093c5317124cea717ae5b224ad67d3b5a04e203ced15401c69740907e4bcc8bcbe8499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_webhook_secret: <%= ENV["GITHUB_WEBHOOK_SECRET"]
  github_integration_private_key: <%= ENV["GITHUB_INTEGRATION_PRIVATE_KEY"]
